/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bpii_ders1;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

public class DeleteStudentPage extends javax.swing.JPanel {

    JFrame mainFrame;
    
    // this keeps the teacher variable during the progam
    Teacher teacher;
    
    ArrayList<Student> students; // all students
    DefaultListModel<String> studentListModel;
    /**
     * Creates new form DeleteStudentPage
     */
    public DeleteStudentPage( JFrame mainFrame, Teacher teacher) {
        initComponents();
        this.mainFrame = mainFrame;
        this.teacher = teacher;
        
        // show the students to the user.
        studentListModel = new DefaultListModel<>();
        Student student = new Student();
        // get all students from the db using student object.
        students = student.getAllStudents();
        
        // add students to the model one by one.
        for( int i = 0; i < students.size(); i++){
            studentListModel.addElement( students.get(i).getStudentId());
        }
        
        studentList.setModel(studentListModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentList = new javax.swing.JList<>();
        successLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        printText = new javax.swing.JButton();

        backButton4.setText("Geri");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Öğrenci Sil");

        jLabel3.setText("Öğrenci Seçiniz");

        jScrollPane1.setViewportView(studentList);

        deleteButton.setText("Sil");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        printText.setText("Dosyaya Yaz");
        printText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(successLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(242, 242, 242)
                            .addComponent(backButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(printText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton4)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
        this.mainFrame.getContentPane().removeAll();
        this.mainFrame.setContentPane(new TeacherPage(mainFrame, teacher) );
        this.mainFrame.invalidate();
        this.mainFrame.validate();
    }//GEN-LAST:event_backButton4ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = studentList.getSelectedIndex();
            
        if( selectedIndex >= 0 ){
            // remove all elements from the model.
            studentListModel.removeAllElements();
            // delete student from the db
            students.get(selectedIndex).delete();
            // remove given student from the student list. 
            students.remove(selectedIndex);
            // create the model without deleted student.
            for( int i = 0; i < students.size(); i++){
                studentListModel.addElement(students.get(i).getStudentId());
            }
            
            successLabel.setText("Öğrenci başarılı bir şekilde silinmiştir.");
            
        }
        else{        
            successLabel.setText("Öğrenci seçiniz.");
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void printTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printTextActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            // create a student list file.
            FileWriter myWriter = new FileWriter("student-list.txt");
            // write all students to that file one by one.
            for(int i = 0; i < students.size(); i++){
                myWriter.write("id: " + students.get(i).getStudentId() + " name: " + students.get(i).getName()+ " surname: " + students.get(i).getSurname() + "\n");            
            }
            myWriter.close();
            successLabel.setText("Dosyaya yazdırıldı.");
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_printTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton4;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printText;
    private javax.swing.JList<String> studentList;
    private javax.swing.JLabel successLabel;
    // End of variables declaration//GEN-END:variables
}
