/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bpii_ders1;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

public class EditFinalGradePage extends javax.swing.JPanel {

    JFrame mainFrame;
    // this keeps the teacher variable during the progam
    Teacher teacher;
    ArrayList<Student> students;
    TakenFinalGrades grades[];
    DefaultTableModel tableModel;
    /**
     * Creates new form EditFinalGradePage
     */
    public EditFinalGradePage( JFrame mainFrame, Teacher teacher) {
        initComponents();
        this.mainFrame = mainFrame;
        this.teacher = teacher;
        
        // create a JTable to show the students and grades
        tableModel = new DefaultTableModel(0, 0);

        // add header of the table
        String header[] = new String[] { "id", "not" };
   
        tableModel.setColumnIdentifiers(header);
        jTable1.setModel(tableModel);
        
        // get all students from the db using student object.
        Student student = new Student();
        students = student.getAllStudents();
        
        // get all final grades of the students from the db.
        TakenFinalGrades grade = new TakenFinalGrades();
        grades = grade.getAllFinalGrades();
        
        // add students to the model with their grade one by one.
        for( int i = 0; i < students.size(); i++ ){
            
            tableModel.addRow(new Object[] { students.get(i).getId(), grades[students.get(i).getId()].getGrade()});
        }
        // if a grade is edited, then update it in the list. 
        tableModel.addTableModelListener( new TableModelListener(){
            @Override
            public void tableChanged( TableModelEvent e){
                int col = jTable1.getSelectedColumn();
                int row = jTable1.getSelectedRow();
                
                if( col == 1){
                    float grade = Float.parseFloat( ( String) tableModel.getValueAt(row, col) );
                    // update the grade in the db.
                    TakenFinalGrades gradeObject = new TakenFinalGrades( students.get(row).getId(), teacher.getId(), grade);
                    gradeObject.addToDb();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        backButton4.setText("Geri");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Final Notu Düzenle");

        jLabel3.setText("Notu Seçip Düzenleyiniz");

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(backButton4)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(backButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
        this.mainFrame.getContentPane().removeAll();
        this.mainFrame.setContentPane(new TeacherPage(mainFrame, teacher) );
        this.mainFrame.invalidate();
        this.mainFrame.validate();
    }//GEN-LAST:event_backButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
