/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bpii_ders1;

import java.util.ArrayList;
import javax.swing.JFrame;

public class TeacherPage extends javax.swing.JPanel {

    JFrame mainFrame;
    Teacher teacher;
    /**
     * Creates new form TeacherPage
     */
    public TeacherPage( JFrame mainFrame, Teacher teacher) {
        initComponents();
        this.mainFrame = mainFrame;
        this.teacher = teacher;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addMidtermGradeButton = new javax.swing.JButton();
        editMidtermGradeButton = new javax.swing.JToggleButton();
        back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addFinalGradeButton = new javax.swing.JButton();
        editFinalGradeButton = new javax.swing.JToggleButton();

        jLabel1.setText("Öğretmen");

        addMidtermGradeButton.setText("Vize Notu Ekle");
        addMidtermGradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMidtermGradeButtonActionPerformed(evt);
            }
        });

        editMidtermGradeButton.setText("Vize Notu Düzenle");
        editMidtermGradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMidtermGradeButtonActionPerformed(evt);
            }
        });

        back.setText("Geri");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jButton1.setText("Öğrenci Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Öğrenci Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        addFinalGradeButton.setText("Final Notu Ekle");
        addFinalGradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFinalGradeButtonActionPerformed(evt);
            }
        });

        editFinalGradeButton.setText("Final Notu Düzenle");
        editFinalGradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFinalGradeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(editMidtermGradeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addMidtermGradeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addFinalGradeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editFinalGradeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMidtermGradeButton)
                    .addComponent(addFinalGradeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editMidtermGradeButton)
                    .addComponent(editFinalGradeButton))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.mainFrame.getContentPane().removeAll();
        this.mainFrame.setVisible(false);
        //this.dispose();
        new Main().setVisible(true);
        this.mainFrame.invalidate();
        this.mainFrame.validate();
    }//GEN-LAST:event_backActionPerformed

    private void addMidtermGradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMidtermGradeButtonActionPerformed
        // TODO add your handling code here:
        this.mainFrame.getContentPane().removeAll();
        this.mainFrame.setContentPane(new AddMidtermGradePage(mainFrame, teacher));
        this.mainFrame.invalidate();
        this.mainFrame.validate();
    }//GEN-LAST:event_addMidtermGradeButtonActionPerformed

    private void editMidtermGradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMidtermGradeButtonActionPerformed
        // TODO add your handling code here:
        this.mainFrame.getContentPane().removeAll();
        this.mainFrame.setContentPane(new EditMidtermGradePage(mainFrame, teacher));
        this.mainFrame.invalidate();
        this.mainFrame.validate();
    }//GEN-LAST:event_editMidtermGradeButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.mainFrame.getContentPane().removeAll();
        this.mainFrame.setContentPane(new AddStudentPage(mainFrame, teacher));
        this.mainFrame.invalidate();
        this.mainFrame.validate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addFinalGradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFinalGradeButtonActionPerformed
        // TODO add your handling code here:
        this.mainFrame.getContentPane().removeAll();
        this.mainFrame.setContentPane(new AddFinalGradePage(mainFrame, teacher));
        this.mainFrame.invalidate();
        this.mainFrame.validate();
    }//GEN-LAST:event_addFinalGradeButtonActionPerformed

    private void editFinalGradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFinalGradeButtonActionPerformed
        // TODO add your handling code here:
        this.mainFrame.getContentPane().removeAll();
        this.mainFrame.setContentPane(new EditFinalGradePage(mainFrame, teacher));
        this.mainFrame.invalidate();
        this.mainFrame.validate();
    }//GEN-LAST:event_editFinalGradeButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.mainFrame.getContentPane().removeAll();
        this.mainFrame.setContentPane(new DeleteStudentPage(mainFrame, teacher));
        this.mainFrame.invalidate();
        this.mainFrame.validate();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFinalGradeButton;
    private javax.swing.JButton addMidtermGradeButton;
    private javax.swing.JButton back;
    private javax.swing.JToggleButton editFinalGradeButton;
    private javax.swing.JToggleButton editMidtermGradeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
